version: "3"

services:
  node:
    build: .
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: ngcash_test
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3010:3010
    environment:
      JWT_SECRET: secretJWT
  db:
    container_name: ngcash_test_db
    image: postgres
    platform: linux/x86_64
    restart: always
    ports:
      - 5432:5432
      - 3306:3306
    environment:
      POSTGRES_PASSWORD: 415263
      POSTGRES_USER: root
      POSTGRES_DB: ng_db


